[package]
name = "hive_lineage"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlparser = "=0.59.0"
anyhow = "1"
itertools = "0.13"
once_cell = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
pretty_assertions = "1"
