[server]
host = "0.0.0.0"
port = 8080
# Number of worker threads for the async runtime
worker_threads = 4

[database]
host = "localhost"
port = 5432
dbname = "lineage"
user = "lineage"
password = "lineage"
# Maximum number of connections in the pool
pool_size = 2

[logging]
log_dir = "./logs"
log_level = "info"
max_log_files = 7
